version : 1

# Language
languages:
  supportedLanguages:
    - &default
      locale: en_GB
      code: en
    -
      locale: fr_FR
      code: fr
    -
      locale: de_DE
      code: de
    -
      locale: it_IT
      code: it
    -
      locale: es_ES
      code: es
    -
      locale: br_FR
      code: br
      fallback:
        - fr_FR
    -
      locale: ca_ES
      code: ca
      fallback:
        - es_ES
  defaultLanguage: *default

autocomplete:
  suggest:
    max_items: 8

layout:
  sizes:
    panelWidth : 400
    topBarHeight: 100
    sideBarWidth: 96
  mobile:
    breakPoint: 640

# Pois
pois:
- apiName: opening_hours
  panelName: hour
  options:
    title: _('Opening hours')
    messages:
      open:
        msg: _('Open')
        color: '#60ad51'
      # soon:
      #   msg: _('Closing soon')
      #   time: 60
      #   color: '#c45713'
      closed:
        msg: _('Closed')
        color: '#8c0212'
- apiName: happy_hours
  panelName: hour
  options:
    title: _('Happy hours')
    messages:
      open:
        msg: _('happy hours!')
        color: '#fcc035'
      soon:
        msg: _('Last pint')
        time: 60
        color: '#3f76e2'
      closed:
        msg: _('Closed')
        color: '#8c0212'
- apiName: website
  panelName: website
- apiName: wikipedia
  panelName: wiki
- apiName: services_and_information
  panelName: services_information
- apiName: information
  panelName: informations
- apiName: accessibility
  panelName: accessibility
  options:
    -
      key: wheelchair
      labels:
        yes: _('Wheelchair accessible')
        partial: _('Partially wheelchair accessible')
        no: _('Not wheelchair accessible')
    -
      key: toilets_wheelchair
      labels:
        yes: _('Wheelchair accessible toilets')
        partial: _('Partial wheelchair accessible toilets')
        no: _('No wheelchair accessible toilets')
- apiName: brewery
  panelName: brewery
- apiName: internet_access
  panelName: internet_access
- apiName: contact
  panelName: contact
- apiName: images
  panelName: images

# Map
map:
  zoom: 2
  center:
    lng: 2.52
    lat: 52.41
  pois_layers: ['poi-level-3', 'poi-level-2', 'poi-level-1']
  routes_layer: "poi-level-street-furniture"

menu:
  - sectionName : _('Qwant is also')
    icon: hash
    links:
    - name : _('Qwant.com')
      uri : https://www.qwant.com/
    - name : _('Qwant Music')
      uri : https://www.qwant.com/music/
    - name: _('Qwant boards')
      uri : https://boards.qwant.com/
    - name: _('Qwant on Android')
      uri : https://play.google.com/store/apps/details?id=com.qwant.liberty
    - name: _('Qwant on iOS')
      uri : https://itunes.apple.com/app/qwant/id924470452
    - name: _('Qwant Junior')
      uri : https://www.qwantjunior.com/
    - name: _('Qwant Lite')
      uri : https://lite.qwant.com/
  - sectionName : _('About Qwant')
    icon: user
    links:
    - name: _('Blog')
      uri : https://blog.qwant.com/fr/
    - name: _('Press')
      uri : https://about.qwant.com/press/
    - name: _('Jobs')
      uri : https://about.qwant.com/jobs/
    - name: _('F.A.Q.')
      uri : https://help.qwant.com/
    - name: _('Maps legal notices')
      uri : https://about.qwant.com/fr/legal/cgu/qwant-maps/
    - name: _('Terms of Service')
      uri : https://about.qwant.com/legal/terms-of-service/qwant-search/
    - name: _('About us')
      uri : https://about.qwant.com/
    - name: _('Privacy')
      uri : https://about.qwant.com/legal/privacy/
    - name: _('Results ranking')
      uri : https://about.qwant.com/fr/legal/modalites-de-referencement-dereferencement-et-de-classement/
  - sectionName : _('Contact us')
    icon: at-sign
    uri : https://about.qwant.com/contact/
  - sectionName : _('Share Qwant')

    icon: share-2
    links:
    - name: _('on Twitter')
      uri : https://twitter.com/share?url=https://www.qwant.com/&text=Why%20allowing%20from%20a%20search%20engine%20something%20you%20won%27t%20in%20real%20life?&hashtags=switchToQwant&via=Qwant_FR #TODO update to maps
    - name: _('on Facebook')
      uri : http://www.facebook.com/sharer.php?u=https://www.qwant.com/

# Types
CATEGORY_TYPE: 'category'
