version : 1

# Language
languages:
  supportedLanguages:
    - &default
      locale: en_GB
      code: en
    -
      locale: en_US
      code: en
    -
      locale: fr_FR
      code: fr
    -
      locale: de_DE
      code: de
    -
      locale: it_IT
      code: it
    -
      locale: es_ES
      code: es
    -
      locale: br_FR
      code: br
      fallback:
        - fr
    -
      locale: ca_ES
      code: ca
      fallback:
        - es
  defaultLanguage: *default

localizedUrls:
  en:
    aboutHome: https://about.qwant.com
    aboutPrivacy: https://about.qwant.com/legal/privacy
    aboutMapsToS: https://about.qwant.com/legal/terms-of-service/qwant-maps/
    contributing: https://github.com/Qwant/qwantmaps/blob/master/contributing.md
    helpGeolocation: https://help.qwant.com/en/docs/maps/activation-of-geolocation-after-denied-access/
    helpEditData: https://help.qwant.com/en/docs/maps/how-to-add-or-modify-data/
  fr:
    helpGeolocation: https://help.qwant.com/docs/maps/activation-de-la-geolocalisation-apres-refus/
    helpEditData: https://help.qwant.com/docs/maps/comment-ajouter-ou-modifier-des-donnees/
  de:
    helpGeolocation: https://help.qwant.com/de/docs/maps/aktivierung-der-standorterfassung-nach-ablehnung/
    helpEditData: https://help.qwant.com/de/docs/maps/wie-kann-ich-daten-hinzufuegen-oder-bearbeiten/
  it:
    helpGeolocation: hhttps://help.qwant.com/it/docs/maps/attivazione-della-geolocalizzazione-dopo-il-rifiuto/
    helpEditData: https://help.qwant.com/it/docs/maps/come-aggiungere-o-modificare-dati/

# Map
map:
  zoom: 2
  center:
    lng: 2.52
    lat: 52.41
  pois_layers: ['poi-level-3', 'poi-level-2', 'poi-level-1', 'poi-level-no-name', 'poi-level-street-furniture']
  routes_layer: "poi-level-street-furniture"

sources:
  osm: 'osm'
  pagesjaunes: 'pages_jaunes'

# Types
CATEGORY_TYPE: 'category'
